#!/bin/sh

# Fail on error
set -e

while true
do
    # Start New Relic
    /opt/bref/sbin/newrelic-daemon -c /opt/bref/etc/newrelic/newrelic.cfg
    # We redirect stderr to stdout so that everything
    # written on the output ends up in Cloudwatch automatically
    /opt/bin/php "/opt/bref/bootstrap.php" 2>&1
done
